// Angel Number Sequences — content data
// Source: "Angel Number Sequences — A Deeper Guide" (co-created doc)
// Voice preserved as written.

const INTRO = `Numbers have carried meaning across every major civilization. The Pythagoreans believed numbers were the language of the universe itself. The Kabbalists mapped creation through the ten Sefirot. Vedic seers encoded cosmic truths in numerical mantras. The Chinese built entire philosophical systems around number harmony.

When you see repeating numbers, you can dismiss it as pattern recognition, and you'd be partially right. But here's the thing: pattern recognition is exactly how humans have always navigated reality. The question isn't whether the pattern is "real." The question is whether paying attention to it makes you more aware, more intentional, more aligned with what you're building.

These aren't fortune cookies. Treat them as mirrors: moments when the noise drops and you catch a reflection of where you actually are.`;

const OUTRO = `These numbers are mirrors, not commands. When you see them, the most valuable thing you can do is pause, even for three seconds, and honestly ask: what is true about my life right now that I'm not looking at? The number points to the territory. You still have to walk it.`;

// Triple sequences. Each: number, title, traditions, signal, body[], asks
const TRIPLES = [
  {
    n: "111", title: "Genesis Point",
    traditions: `In Kabbalah, 1 corresponds to Kether (Crown), the first emanation, pure undifferentiated will before it takes form. Pythagoras called 1 the Monad, the source from which all numbers (and therefore all things) emerge. In Hinduism, the syllable Om is considered the "one sound" that preceded creation.`,
    signal: `You are at an origin point. Not metaphorically, right now, the thoughts and intentions you're holding are unusually potent. Whatever you're focused on is gaining momentum faster than normal.`,
    body: [`This is not a gentle "think positive" reminder. It's a warning and an opportunity simultaneously. The snapshot is being taken now. If your mind is running on fear, scarcity, or resentment, that's what's being amplified. If it's running on clarity, purpose, and conviction, that's what accelerates.`],
    asks: `Audit your inner monologue honestly. Not what you wish you were thinking, what you're actually thinking. Correct it if needed. Then choose one intention and hold it clearly. This is a doorway, and doorways don't stay open forever.`
  },
  {
    n: "222", title: "The Unseen Growth",
    traditions: `2 is the Dyad in Pythagorean thought, the first division, the birth of polarity and relationship. In Kabbalah, Chokmah (Wisdom) is the second Sefirah, representing the flash of insight before it becomes structured. The Tao Te Ching says: "The Tao gives birth to One. One gives birth to Two." Two is where potential begins to take shape, but hasn't yet become visible. In the I Ching, the second hexagram is Kun (The Receptive), pure yin, the earth receiving the seed.`,
    signal: `What you planted is growing, but it's underground. The absence of visible results is not the absence of progress. Roots grow in darkness before anything breaks the surface.`,
    body: [`The hardest part of building anything, a company, a relationship, a new version of yourself, is the period where you've committed but can't yet see evidence that it's working. 222 appears in that exact gap. It's not asking you to be blindly optimistic. It's asking you to trust the process you already started, because pulling up a seed to check if it's growing kills it.`],
    asks: `Patience that isn't passive. Keep watering, keep doing the work, holding the vision, nurturing the relationships. But stop digging up what you planted to inspect it. The evidence will come. Don't quit in the gap.`
  },
  {
    n: "333", title: "The Triangle of Support",
    traditions: `Three is sacred in virtually every tradition. The Christian Trinity (Father, Son, Holy Spirit). The Hindu Trimurti (Brahma the Creator, Vishnu the Sustainer, Shiva the Transformer). The Triple Goddess in Celtic tradition (Maiden, Mother, Crone). Pythagoras considered 3 the first "true" number because it has a beginning, middle, and end, it's the first shape (triangle) and therefore the first form of completeness. In Kabbalah, Binah (Understanding) is the third Sefirah, the womb where raw wisdom takes structure and becomes something real.`,
    signal: `You are not alone in what you're doing, even if it feels like it. There is support around you that you may not be perceiving because you're too deep in the work. This could be spiritual support (if that resonates with you), or it could be people, resources, and opportunities that are already present but that you haven't noticed because your head is down.`,
    body: [`333 also flags alignment, or misalignment, between your mind, body, and spirit. If one of these three is being neglected (usually the body or the spirit when you're building hard), 333 is the nudge to rebalance before the imbalance costs you something.`],
    asks: `Look up from the work for a moment. Who or what is trying to help you that you haven't acknowledged? And which of the three (mind, body, spirit) have you been starving? Feed it today, not next week.`
  },
  {
    n: "444", title: "The Foundation Check",
    traditions: `Four is the number of the material world across traditions. Four elements (earth, water, fire, air). Four cardinal directions. Four seasons. In Kabbalah, Chesed (Mercy/Loving-kindness) is the fourth Sefirah, the first expansion into manifestation. In Buddhism, the Four Noble Truths form the foundation of the entire teaching. The Native American medicine wheel has four quadrants. A table stands on four legs.`,
    signal: `What you're building right now will last, but only if the foundation is solid and honest. 444 shows up when the structural integrity of something in your life needs attention. Not the visible parts. The parts underneath.`,
    body: [`This number is also about protection, but not in a passive way. It's the protection that comes from having done the work correctly. A house with good foundations doesn't need to fear the storm.`],
    asks: `Look at whatever you're constructing, a business, a relationship, a plan, and ask: is the foundation true? Are there shortcuts you took that you know will create problems later? Are there conversations you're avoiding that would make the structure stronger? Fix the foundation now, while it's still easy. Later, it won't be.`
  },
  {
    n: "555", title: "The Disruption That Serves You",
    traditions: `Five is the human number. Five senses. Five fingers. Da Vinci's Vitruvian Man is drawn inside a pentagram. In Kabbalah, Geburah (Severity/Discipline) is the fifth Sefirah, the force that cuts away what doesn't belong, sometimes painfully, always necessarily. In Tarot, the Hierophant (card 5) bridges heaven and earth, translating divine order into human experience. The Chinese Wu Xing describes five transformative phases of energy.`,
    signal: `A major shift is coming or already underway. This is not random chaos. You are being reshaped to match who you are becoming, and the old form has to break for the new one to emerge.`,
    body: [`555 doesn't promise the change will be comfortable. Geburah is the surgeon's knife: precise, necessary, and it cuts. But every significant growth you've ever experienced required something to break first. The caterpillar doesn't "improve" into a butterfly. It dissolves completely and reforms.`],
    asks: `Stop bracing against the change and start asking what it's making room for. The thing you're losing or the ground that's shifting, what would you build in that space if you had permission to start fresh? Because that's exactly what's happening. Stay flexible, stay centered, and ride it through.`
  },
  {
    n: "666", title: "Return to Center",
    traditions: `Far from being "evil," 6 is the number of harmony and beauty in most traditions. In Kabbalah, Tiferet (Beauty/Harmony) is the sixth Sefirah, the heart center of the entire Tree of Life, the place where mercy and severity balance. The Star of David (hexagram) is two interlocking triangles: "as above, so below." In Pythagorean numerology, 6 is the first "perfect number" (1+2+3=6, and 1×2×3=6), a number in complete harmony with itself. Carbon, the basis of all life, has 6 protons.`,
    signal: `You've drifted off center. Your attention has been consumed by material concerns, money, status, possessions, work output, to the point where your inner life is starving. Or the reverse: you've been so in your head or in spiritual bypass that practical reality is falling apart.`,
    body: [`The association of 666 with evil comes from a single passage in Revelation, likely a coded political reference to Emperor Nero (whose name in Hebrew gematria equals 666). The number itself, across thousands of years of numerological tradition, means balance, responsibility, and the beauty that emerges when opposites integrate.`, `666 is the heart of the Tree for a reason. It's the integration point. Not heaven OR earth. Heaven AND earth, held in balance.`],
    asks: `Identify which direction you've drifted and correct it. If you've been grinding on material goals, stop and reconnect with why you're doing any of this. If you've been avoiding practical responsibilities, ground yourself in action. The answer is always in the center, not at the extremes.`
  },
  {
    n: "777", title: "Earned Alignment",
    traditions: `Seven is perhaps the most universally sacred number. Seven days of creation. Seven chakras. Seven notes in the musical scale. Seven classical planets. In Kabbalah, Netzach (Victory/Endurance) is the seventh Sefirah, and "victory" here doesn't mean winning a competition. It means prevailing through persistence, the kind of triumph that comes from outlasting, not outsmarting. In Judaism, the seventh day (Shabbat) is rest, not as reward but as completion of the creative cycle.`,
    signal: `You've earned something. Not through a clever hack or a lucky break, but through sustained effort, right choices, and endurance. The universe is acknowledging that. This is rare, most of life doesn't give you a scoreboard. 777 is the scoreboard lighting up.`,
    body: [`But there's a second layer. Seven is also the number of inner wisdom and the invitation to go deeper. You may be at a point where external success is flowing, but your inner life, your spiritual development, your self-knowledge, is calling for equal attention. Don't let momentum become a treadmill.`],
    asks: `Receive the acknowledgment. You've been doing the work, and it's working. But also: pause. Seven completes a cycle. What have you learned that you haven't yet integrated? What wisdom are you carrying that you haven't applied to your own life? The world doesn't need you to go faster right now. It needs you to go deeper.`
  },
  {
    n: "888", title: "The Harvest",
    traditions: `In Chinese culture, 8 (八, bā) sounds like "prosper" (發, fā) and is considered the luckiest number. Beijing's Olympics opened on 08/08/08 at 8:08 PM. In Kabbalah, Hod (Splendor/Intellectual Beauty) is the eighth Sefirah. In Christianity, 8 represents resurrection and new creation: circumcision on the 8th day, Jesus rose on the 8th day (the day after the 7th/Sabbath), baptismal fonts have 8 sides. The number 8 turned sideways is ∞, infinity.`,
    signal: `You are entering a harvest phase. The work you've put in is producing tangible returns, financial, relational, reputational, or all three. But every harvest also marks the end of a growing season. Something is completing.`,
    body: [`888 carries the energy of infinite cycles. What's ending isn't dying, it's completing a loop and preparing to begin again at a higher level. The abundance coming to you now isn't just for you to accumulate. It's also to be shared, reinvested, and used as fuel for the next cycle.`],
    asks: `Collect what you've earned, don't be humble about receiving it, and don't procrastinate. But also: recognize what's completing. What phase of your life is reaching its natural conclusion? Don't cling to it out of comfort. The harvest means the season is changing, and the next planting is coming. Be generous with what you've received, and be ready for what's next.`
  },
  {
    n: "999", title: "Completion",
    traditions: `Nine is the number of completion across traditions. Nine months of human gestation. In Norse mythology, nine worlds hang on Yggdrasil (the World Tree). In Kabbalah, Yesod (Foundation) is the ninth Sefirah, the gateway between the material and spiritual worlds, the last step before manifestation. In the Bahá'í Faith, 9 represents completeness as the highest single digit. The Enneagram maps nine personality archetypes as a complete map of human motivation.`,
    signal: `A major chapter is done. Fully done. Not paused, not on hold, complete. This might be a relationship, a career phase, a way of thinking, a version of yourself that you've outgrown. The signal is clear: stop trying to extend what has already finished.`,
    body: [`Mathematically, 9 has a unique property: any number multiplied by 9 has digits that sum back to 9 (9×2=18, 1+8=9; 9×7=63, 6+3=9). Nine always returns to itself. It is the number that contains everything.`, `999 is also a call to service. When one cycle completes, there's a brief window where you have both the wisdom of what you've learned and the freedom of not yet being committed to the next thing. That window is powerful. Use it.`],
    asks: `What are you holding onto that's already over? Name it honestly. Then let it go, with gratitude, not with grief. It completed. It didn't fail. There's a difference. And before you rush into the next thing, ask: what did this chapter teach me that I'm meant to share?`
  },
  {
    n: "000", title: "The Void Before Creation",
    traditions: `Zero was a revolutionary concept. The Mayans and Indians discovered it independently, and it changed mathematics forever. In Kabbalah, before the ten Sefirot there is Ein Sof, the Infinite, limitless, without form or boundary. In Buddhism, Śūnyatā (emptiness) is not nothingness but the pregnant void from which all phenomena arise. The Ouroboros (the serpent eating its tail) represents this same idea: the cycle with no beginning and no end. In Taoism, the Tao that can be named is not the Tao, the origin of all things is formless.`,
    signal: `You've come full circle. A situation has returned to its origin point, or you've arrived at a moment of pure potential, no momentum in any direction, no obligations pulling you, just openness. This is the most powerful and the most terrifying state.`,
    body: [`000 is the cosmic reset. It doesn't tell you what's coming because nothing is determined yet. You are standing in the space before creation, where everything is possible precisely because nothing is fixed.`],
    asks: `Don't rush to fill the void. Sit in it. Feel the discomfort of unlimited possibility without grabbing for the first thing that looks like certainty. The quality of what you create next depends entirely on how present you are in this moment of emptiness. Breathe. Connect to whatever you call the source. Then, when the first true impulse arises, not from fear, not from habit, but from genuine knowing, follow it.`
  }
];

// Combinations matrix. key: "a+b". Also store the example triplets for direct search.
const COMBOS = [
  { pair:"1+2", ex:["112","121","212"], text:`In the Tarot, the Magician (1) works with the High Priestess (2): will meeting intuition, action meeting receptivity. Your intentions have taken root and the first shoots are emerging. You may already see small evidence. This isn't the time to pivot or second-guess, it's the time to keep watering what you planted. The early signs are real. Ask yourself: What small evidence have I dismissed? Look again, the proof you need may already be in front of you.` },
  { pair:"1+3", ex:["113","131","313"], text:`The Pythagoreans saw 1 as the Monad (source) and 3 as the first complete form: together they represent creation guided by wisdom. Higher wisdom is actively informing your creative process right now. Ideas arriving in flashes, sudden clarity about your path, unexpected insights, these aren't random. You're being mentored from a level you may not fully see. Ask yourself: What intuitive idea have I received recently but not acted on? That's the signal. Follow it.` },
  { pair:"1+4", ex:["114","141","411"], text:`In Kabbalah, Kether (1, pure will) channeled through Chesed (4, structured expansion) means intention becoming architecture. Your thoughts are manifesting with unusual speed and precision, a gateway is open. Set a clear intention today, not someday. The sequence 411 specifically means: you need information you don't have. Ask for it, from guides, mentors, or simply by researching what's been nagging at you. Ask yourself: If I could plant one seed right now that would grow into exactly what I need, what would it be? Name it. Then hold that thought clearly.` },
  { pair:"1+5", ex:["115","151","515"], text:`In the I Ching, change (5's energy) initiated by conscious will (1's energy) is the most powerful form of transformation: deliberate, not accidental. The changes happening around you are being driven by your own thoughts, whether you realize it or not. You are co-creating this shift. Ask yourself: Am I steering toward what I want, or reacting to what I fear? If the changes ahead aren't what you desire, redirect your focus now, you still have the wheel.` },
  { pair:"1+6", ex:["116","161","611"], text:`In Kabbalah, Kether (1) and Tiferet (6) are connected by the central pillar, the direct channel between divine will and the heart. Material anxiety is blocking that channel. The worry itself is the problem, not the situation you're worried about. Shift your focus upward, reconnect with purpose, service, or gratitude, and solutions will find you faster than your worrying can find them. 611 specifically: ask for help fixing the material thing that's irritating you. Ask yourself: What am I worried about that I could hand over, to a person, a process, or simply to trust? Do that today.` },
  { pair:"1+7", ex:["117","171","711"], text:`Seven is Netzach in Kabbalah (Victory through endurance), and paired with 1 (new beginnings), it means your persistence is producing real results. Confirmation that your choices have been correct. You've been thinking clearly and acting with integrity, and it's working. Add genuine gratitude to the mix, not performance, but real appreciation for what's already here. That frequency accelerates everything you're building. Ask yourself: What's working right now that I haven't paused to acknowledge? Acknowledge it. Then do more of exactly that.` },
  { pair:"1+8", ex:["118","181","811"], text:`Eight is Hod in Kabbalah (Splendor/Completion) and paired with 1 (genesis), it means an ending that births something new, the phoenix dynamic. A tired chapter is ending to make room for something better. If part of your life has felt like dragging a weight, relief is coming. The new thing can't arrive while your hands are full of the old thing. Ask yourself: What am I keeping alive out of obligation or habit that has actually already ended? Name it. Then begin loosening your grip.` },
  { pair:"1+9", ex:["119","191","911"], text:`Nine is Yesod in Kabbalah, the foundation, the gateway between worlds. Paired with 1, it means one reality dissolving so another can crystallize. A door is opening because another just closed. Your thoughts created both the ending and the beginning. Don't look back at the closed door, face the open one. Ask yourself: What new thing has been waiting for me to stop mourning the old thing? Turn toward it today.` },
  { pair:"1+0", ex:["100","101","110"], text:`Zero is Ein Sof, the infinite, formless potential. Paired with 1, it means the Divine is directly shaping your thought-seeds before they manifest. This is a course correction, not because you're failing, but because you're being guided toward a better version of what you asked for. The universe is saying "yes, but aim higher" or "yes, but start with your mindset first." Ask yourself: What have I been asking for that might be too small? What would the upgraded version look like?` },
  { pair:"2+3", ex:["223","232","322"], text:`In the Vedic tradition, the guru-student relationship is considered sacred co-creation, the teacher doesn't just instruct, they build with the student. That's what's happening here. You're co-creating something with forces larger than yourself, and they're as invested in the outcome as you are. This isn't you working and hoping for the best, this is active collaboration with the unseen. Ask yourself: Where am I trying to do it all alone when I actually have invisible partners? Let them contribute. Your job is to stay open and keep moving.` },
  { pair:"2+4", ex:["224","242","422"], text:`In A Course in Miracles: "The angels nurse your newborn purpose." The Talmud teaches that every blade of grass has an angel that bends over it and whispers "grow." Your new purpose or direction is being cradled and protected right now. You may feel fragile or uncertain, that's normal for beginnings. The vulnerability is the proof that something real has started. Ask yourself: What new thing in my life feels fragile right now? Protect it. Don't expose it to critics or doubters first. Let it strengthen first.` },
  { pair:"2+5", ex:["225","252","522"], text:`In Taoism, the sage doesn't force the river, but when the current accelerates, they adjust their position and ride it. Your clear intention has set something in motion faster than you expected. Don't let the speed scare you, and don't insist it arrive in the exact form you imagined. It may come through an unexpected door. Ask yourself: Am I attached to how this should arrive, or am I truly open to receiving it however it comes? Loosen the grip on the form. Keep the grip on the faith.` },
  { pair:"2+6", ex:["226","262","622"], text:`Six is the number of material harmony, the hexagon appears in honeycombs, crystals, and molecular structures because it's nature's most efficient form. Paired with 2 (manifestation emerging), something tangible is coming to you, a resource, acquisition, or financial shift. The manifestation process has reached the physical plane. Ask yourself: Am I ready to receive? Sometimes we block material blessings because we don't feel we deserve them. Open your hands.` },
  { pair:"2+7", ex:["227","272","722"], text:`Seven in Hebrew tradition is "sheva," closely related to "sova" (satisfaction, fullness). Paired with 2 (patience, trust), this signals that what you're waiting for, an answer, a decision, an approval, is trending in your favor. The outcome is being arranged behind the scenes. Ask yourself: Can I wait without wavering? The answer is coming. Your only job is to not lose faith in the interim.` },
  { pair:"2+8", ex:["228","282","822"], text:`The infinity symbol (8) is also the lemniscate, the figure-eight path that loops between two poles. Paired with 2 (duality, choice), you're standing in a doorway. One space closing, one opening ahead. Your intuition is your best navigator right now, logic is useful, but intuition is faster in transitions. Ask yourself: What is my gut telling me to do that my rational mind keeps overruling? Trust the gut this time.` },
  { pair:"2+9", ex:["229","292","922"], text:`In Buddhism, the concept of pratītyasamutpāda (dependent origination) teaches that nothing arises or ceases independently, every ending contains the seed of what comes next. If you've suffered a recent loss, it's making space for something significantly better. The rearrangement happening behind the scenes is more extensive than you can see. This isn't punishment, it's preparation. Ask yourself: What seed is hidden inside this loss? Don't answer from grief. Answer from curiosity.` },
  { pair:"2+0", ex:["200","202","020"], text:`In Psalm 139: "Where can I go from your Spirit? Where can I flee from your presence?" Zero (God/Source) paired with 2 (trust, patience) is a direct message: you are not forgotten and you are not abandoned. What you're waiting for requires other pieces to fall into place first, and they are being arranged. Divine timing isn't delay, it's precision. Ask yourself: What if the delay IS the answer, the universe saying "not yet, because something better is being prepared"? Can I trust that?` },
  { pair:"3+4", ex:["334","343","433"], text:`In Hinduism, 3 represents Brahma-Vishnu-Shiva (creation-preservation-transformation) and 4 represents the four Vedas (complete knowledge). Together: the full power of creation backed by complete wisdom. Maximum support is available to you right now, both the insight of teachers and the protection of guardians. Whatever challenge you're facing, you have more help than you realize. Ask yourself: Have I actually asked for help, or am I just hoping it arrives? Ask. Out loud, in prayer, in a message to someone. The help is there, but you need to reach for it.` },
  { pair:"3+5", ex:["335","353","533"], text:`In the Celtic tradition, the triple spiral (triskele) represents movement through cycles, birth, death, rebirth, always in motion, always purposeful. The masters who guide you (3) are preparing you for a significant change (5). They see further than you can and they're holding your hand through this. The change is for your benefit, even when it feels disorienting. Ask yourself: What part of this change am I resisting because it's unfamiliar? Look for the blessing embedded in the disruption, it's there.` },
  { pair:"3+6", ex:["336","363","633"], text:`In Kabbalah, Binah (3, Understanding) flowing into Tiferet (6, Beauty/Heart) represents wisdom becoming tangible provision: the universe providing what's needed for sacred work. The resources you need to fulfill your purpose are being arranged, money, tools, connections, platforms. This isn't luck; it's infrastructure for your mission. Ask yourself: Am I blocking myself from receiving because I feel I should struggle? Accept what's offered without guilt. Receiving these resources amplifies your ability to give.` },
  { pair:"3+7", ex:["337","373","733"], text:`Three and seven together appear in virtually every sacred tradition: three days and seven seals in Revelation, three jewels and seven factors of awakening in Buddhism, three gunas and seven chakras in Hinduism. This combination signals deep alignment. You're on your soul's path, and higher wisdom is celebrating your choices. If you've been doubting, stop. Ask yourself: What joy have I been blocking because I felt it wasn't "earned" yet? The joy IS the confirmation. Let it in.` },
  { pair:"3+8", ex:["338","383","833"], text:`In martial arts philosophy, the concept of "zanshin" (残心) means maintaining awareness and energy through the final moment of an action, never quitting at 90%. You're close to a breakthrough and your energy is flagging. This is exactly the moment to push through, not pull back. Reconnect with the big picture, why you started, what it serves, who it helps. Ask yourself: What would I tell someone else in my position right now? You're closer than you think. Give it the last 10%.` },
  { pair:"3+9", ex:["339","393","933"], text:`In the Bhagavad Gita, Krishna teaches Arjuna about non-attachment: doing what must be done without clinging to outcomes. Let go of what's no longer in integrity. You know what it is. Holding onto it out of fear is costing you more than releasing it ever will. Your future self needs that hand free to grab what's coming next. Ask yourself: What am I keeping out of fear that I'd drop instantly if I truly trusted what's coming? Release it, with love, not resentment.` },
  { pair:"3+0", ex:["300","303","330"], text:`In Sufism, the concept of "himma" is the heart's deepest intention, the thing your soul knows you must do, even when your ego hesitates. God (0) and the masters (3) are trying to get your attention because you're ignoring guidance. There's an intuition, a calling, or a divine prompt you've been aware of but haven't acted on. That's why things feel stuck. Ask yourself: What have I known I should do for weeks (or months) that I keep postponing? The co-creation process needs your participation. Take the first step today.` },
  { pair:"4+5", ex:["445","454","544"], text:`In the Native American tradition, the four directions each have a guardian spirit, and when the winds of change blow (5), those guardians ride with the storm. Your guardians are actively involved in the transition you're going through. This change isn't unsupervised, you may notice synchronicities, timely "coincidences," or a sense of being steered. That's real. Trust it. Ask yourself: What recent "coincidence" did I dismiss as random? Look again, it may be guidance in disguise.` },
  { pair:"4+6", ex:["446","464","644"], text:`In Zen Buddhism, there's a teaching: "Let go, or be dragged." The four elements (4, structure) combined with material concern (6) means you're gripping too hard on outcomes. You're trying to control material results through worry, and it's not working. Hand the anxiety over, to the universe, to your angels, to whatever holds meaning for you. The paradox is real: the less you grip, the more flows. Ask yourself: What one worry could I consciously release today? Not solve, release. Feel the difference.` },
  { pair:"4+7", ex:["447","474","744"], text:`In Pythagorean thought, 4 (structure, discipline) combined with 7 (wisdom, inner knowing) produces "sophia through praxis," wisdom demonstrated through practice. You're being recognized because your focused actions are producing real results. This isn't flattery, it's the universe reflecting back what you've built. Ask yourself: What's working that I should double down on rather than diversify away from? Keep doing exactly this.` },
  { pair:"4+8", ex:["448","484","844"], text:`In Egyptian mythology, Anubis guides souls through the transition between worlds, not to frighten, but to ensure safe passage. Something is ending, and you're being escorted through the transition. The old room served its purpose; the new one is better suited to who you've become. Don't linger in the hallway between them. Ask yourself: Am I stalling in the transition because the new thing feels unfamiliar? Step through. The discomfort of the hallway is worse than either room.` },
  { pair:"4+9", ex:["449","494","944"], text:`In the Buddhist tradition, the "charnel ground" meditation teaches practitioners to sit with endings without flinching, because every ending is also a beginning seen from the other side. Release what's over. The door closed. It wasn't a mistake, and keeping it on life support helps no one. The pain of letting go is real, but so is the relief waiting on the other side. Ask yourself: What am I keeping alive that has already died? Name it with honesty. Then grieve it briefly, and turn toward the new door.` },
  { pair:"4+0", ex:["400","404","440"], text:`In Sufism, "dhikr" is the practice of remembering God, not intellectually, but as a felt presence in the body. This combination is that practice distilled into a number. You are deeply, unconditionally loved. That's the entire message. When you see this, stop for ten seconds and actually feel it. Not as a concept, as a sensation in your chest. Ask yourself: Nothing to ask. Just receive. Let the love land. Many of your current problems will look different from that place.` },
  { pair:"5+6", ex:["556","565","655"], text:`In feng shui, rearranging the physical environment changes the flow of chi (life force) through your life. The 5 (transformation) meeting 6 (material world) means your physical circumstances are shifting, home, possessions, finances, living situation. The universe is rearranging the stage for your next act. Whether it's an upgrade or a simplification, it serves your evolution. Ask yourself: What material change have I been resisting or postponing? This is the green light. Move forward with it.` },
  { pair:"5+7", ex:["557","575","755"], text:`In the Hermetic tradition, "as above, so below" means that when your inner knowing (7) aligns with outer change (5), reality reshapes itself to match. A change you've been sensing is validated, you read the situation correctly. This change will enrich you on multiple dimensions: mentally, emotionally, spiritually, physically. Ask yourself: What change have I been sensing but waiting for permission to act on? This is the permission. Go.` },
  { pair:"5+8", ex:["558","585","855"], text:`In alchemy, the moment before transmutation, when lead is about to become gold, is called the "nigredo," the darkest, most pressurized phase. You're in the final countdown before a major shift. The intensity you feel is compression before expansion. Don't fear it. Tie up loose ends, prepare what you can, and then surrender to the process. Ask yourself: What loose ends can I close today to make this transition cleaner? Do those. Then let go, you're about to break through.` },
  { pair:"5+9", ex:["559","595","955"], text:`In the Japanese concept of "ma" (間), empty space is not absence, it's the container that gives meaning to what fills it. Release the past to receive the future. The new cannot enter while the old occupies the space. This applies to physical clutter, emotional baggage, outdated beliefs, and relationships that have completed their cycle. Ask yourself: What am I holding onto that is taking up space the future needs? Declutter it, externally and internally. What replaces it will be better.` },
  { pair:"5+0", ex:["500","505","550"], text:`In the Islamic tradition, "Qadr" (Divine decree) means that certain events in your life's contract were written before you arrived. The changes happening now are divinely orchestrated, not accidents, not bad luck. They're aligned with a design you'll understand more clearly in retrospect. This is sacred disruption. Ask yourself: Can I accept this change as a gift, even before I understand it? Gratitude in advance of understanding is the highest form of trust.` },
  { pair:"6+7", ex:["667","676","766"], text:`In Kabbalah, Tiferet (6, Beauty/Heart) and Netzach (7, Victory/Endurance) sit side by side on the Tree of Life, the heart and the will. You've found the balance between your material and spiritual lives, and it shows. Mind, body, and spirit are synchronized. This is rare and worth protecting. Ask yourself: What am I doing differently right now that created this balance? Name it consciously, so you can protect and repeat it.` },
  { pair:"6+8", ex:["668","686","866"], text:`In Taoism, Wu Wei (effortless action) includes knowing when to let things go without force. Something material is about to leave your life, a sale, a release, a financial shift. If this is intentional, the transaction will go smoothly. If it's not, check your mindset: are you focused on what you want, or on fear of losing what you have? Ask yourself: Am I clinging to something material out of fear rather than genuine need? If the release is coming, let it be clean. Focus determines outcome.` },
  { pair:"6+9", ex:["669","696","966"], text:`The Buddhist concept of "aparigraha" (non-possessiveness) teaches that the tighter we grip, the less we can hold. Something better is trying to replace what you're gripping, but you have to open your hand first. Ask yourself: What possession, status, or financial goal has become an identity rather than a tool? Let it loosen. You deserve the upgrade that's waiting, but only open hands can receive it.` },
  { pair:"6+0", ex:["600","606","660"], text:`Jesus in the Sermon on the Mount: "Seek ye first the kingdom of God, and all these things shall be added unto you." The Vedas echo this: "Purnam adah, purnam idam," from fullness, fullness comes. Source is your supply, not your job, not your savings, not any external form. This isn't about becoming impractical, it's about where you place your foundational trust. Ask yourself: Where am I placing my security, in a form (job, account, contract) or in the Source behind all forms? When you truly trust the source, the forms multiply.` },
  { pair:"7+8", ex:["778","787","877"], text:`In astrology, the 8th house (Scorpio's domain) rules death, transformation, and rebirth, the deep endings that change everything. Paired with 7 (inner knowing, intuition), this means your gut feeling that something is ending is correct. Trust what you feel. The intensity of this moment is proportional to the relief and expansion that follows. Ask yourself: What have I known is ending but haven't admitted yet? Name it. The completion will bring a lightness you can't currently imagine.` },
  { pair:"7+9", ex:["779","797","977"], text:`The snake sheds its entire skin, not because it's damaged, but because it has outgrown it. In Hindu tradition, the serpent Kundalini rises through seven chakras, shedding limitations at each level. You are shedding a version of yourself that no longer fits. This takes courage, leaving familiar identities behind, even when they've become costumes rather than skin. Ask yourself: What identity am I wearing that used to be real but is now just a costume? The universe applauds your honesty in removing it. Everything that truly belongs in your life will align with the real you.` },
  { pair:"7+0", ex:["700","707","770"], text:`In the Psalms: "Be still, and know that I am God." In Zen: "Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water." This is direct acknowledgment from the highest source, the work you're doing (mental, spiritual, physical) is making a difference for yourself and for others you may not even be aware of. Ask yourself: Nothing to ask. Just receive this: you are seen, you are valued, you are on the right path. Continue.` },
  { pair:"8+9", ex:["889","898","988"], text:`In ecology, a forest fire clears decades of deadwood so new growth can emerge stronger than before, the destruction is part of the renewal cycle. A domino chain of endings is happening. One big chapter closes and takes several related situations with it. This can feel overwhelming, like everything is changing at once. It is. But this clearing is necessary for what comes next, which will be fundamentally different and better. Ask yourself: Instead of trying to save individual pieces, can I trust that the whole landscape is being renewed? Let the dominoes fall. What grows back will be stronger.` },
  { pair:"8+0", ex:["800","808","880"], text:`In Kabbalah, the concept of "tzimtzum" describes how God contracted to make space for creation, divine withdrawal as the ultimate act of love and generosity. The endings happening now are answers to your prayers, even if they don't look like answers. You asked for growth, for something better, and the universe is contracting what was to make room for what will be. Ask yourself: What did I pray for or deeply wish for recently? Now look at what's ending. Can you see the connection? The architect is building what you asked for. Trust the process.` },
  { pair:"9+0", ex:["900","909","990"], text:`In the Hawaiian practice of Ho'oponopono, healing begins with four phrases: "I'm sorry. Please forgive me. Thank you. I love you." This ancient practice recognizes that every ending carries threads that need releasing, not just from others, but from ourselves. What just ended was always meant to end at this point. Nothing was lost, it completed. Your higher self called this change into being, even if your conscious mind is grieving. The single most important thing now: forgive. Everyone involved, including yourself. Forgiveness isn't absolution, it's releasing the weight so you can walk freely into what's next. Ask yourself: Who (including myself) do I need to forgive to walk into the next chapter unburdened? Say the words, even silently. Then step forward. What's next is beautiful.` }
];

const COMBO_INTRO = `When you see blended sequences, the message combines the energies of each number. If you see a three-digit mix (like 312), combine the relevant pairs (3+1 and 1+2), or add all digits to a single number (3+1+2=6) and read that triple sequence for the overarching theme.`;
